### ISSUE TITLE
調整 detail view 的 layout 讓他 fit current design

### ISSUE THREAD

**Issue by kun-yu-tsai** [nexfoundation/vanilla#104]
同時，現在 layout 有些跑掉，需要做一些調整

底下是[設計文件內](https://www.figma.com/file/rOeaDScRLJ5qUAeAqiz4XO/Forum-Design-Submission?node-id=3%3A1046)的版面

<img width="856" alt="Screenshot 2021-03-28 at 17 09 49" src="https://user-images.githubusercontent.com/9505724/112747484-73a04500-8fe8-11eb-9537-a33681630fe2.png">

**Comment by kun-yu-tsai** [comment]
主要有 tag、日期、po 文者資訊

**Comment by blueworrybear** [comment]
@kun-yu-tsai 

I can to this issue, you could assign this one to me.

**Comment by kun-yu-tsai** [comment]
@blueworrybear, 因為 #113 可能也需要你那邊協助看一下，那是和登入有關的一個 bug。

這個 ticket，如果你時間可以，可以再做，我怕你那邊時間不夠安排～，這個我同時也 assign 給 @jeffsyliu 處理。
@jeffsyliu 你那邊要開始弄時，可以再和 Benno sync 一下，看這個 in progress 了沒。

Jeff 這邊除了 #44 #48 還有這個外。如果你時間 okay，再麻煩你處理有關文章大頭貼還有列表下的排版問題，可以看 #110 #111
