### ISSUE TITLE
字體調整。目前字體、大小和設計不同。調了會更好看！

### ISSUE THREAD

**Issue by kun-yu-tsai** [nexfoundation/vanilla#106]
目前看起來需要調整字體大小的 pages：
1. 文章列表
2. detail 文章
3. 編輯器下的 Header size

設計：
<img width="878" alt="Screenshot 2021-03-30 at 04 06 43" src="https://user-images.githubusercontent.com/9505724/112895292-806b8880-910f-11eb-934d-98be1a95d95c.png">

目前：
![Screenshot 2021-03-30 at 04 20 50](https://user-images.githubusercontent.com/9505724/112895301-85303c80-910f-11eb-9d20-3fffb1d2ce60.png)

**Comment by AB-Y** [comment]
目前配置可以，若有大小跟間距問題都有另外再記錄其他 ticket
