### ISSUE TITLE
文章列表，作者沒有大頭貼顯示

### ISSUE THREAD

**Issue by kun-yu-tsai** [nexfoundation/vanilla#110]
建議和 #111 一起

目前
![Screenshot 2021-03-30 at 03 59 46](https://user-images.githubusercontent.com/9505724/112893785-b576db80-910d-11eb-85a9-074e5b0ff17e.png)

設計圖
<img width="823" alt="Screenshot 2021-03-30 at 04 00 09" src="https://user-images.githubusercontent.com/9505724/112893896-d2abaa00-910d-11eb-9a0b-14366c12f134.png">

需要將大頭貼顯示出來

**Comment by AB-Y** [comment]
確認網頁與手機瀏覽，不論是在文章列表或單一文章頁面，大頭照都有顯示
