### ISSUE TITLE
文章列表下，日期位置調整、日期格式調整、作者與大頭貼位置調整

### ISSUE THREAD

**Issue by kun-yu-tsai** [nexfoundation/vanilla#111]
建議和 #110 一起

設計的部分
<img width="841" alt="Screenshot 2021-03-30 at 04 06 34" src="https://user-images.githubusercontent.com/9505724/112893610-7ba5d500-910d-11eb-85ee-84dce761a811.png">

目前
![Screenshot 2021-03-30 at 04 08 01](https://user-images.githubusercontent.com/9505724/112893648-87919700-910d-11eb-939c-3d556629f8f4.png)

需要更改三個部分：
1. 日期位置調整
2. 日期格式調整
3. 作者與大頭貼位置調整

**Comment by blueworrybear** [comment]
@kun-yu-tsai 

I try to put the date on both top-right corner and the bottom-right corner.
Putting the date string on the top-right looks good in the desktop, but weird in mobile view.

It seems to me that putting it in the bottom-right would be a better choice in short-term.
We may need to discuss with @clara-tsao for her feedbacks.

![image](https://user-images.githubusercontent.com/1456219/113502863-51b33f00-9561-11eb-8afc-fe5a77056c02.png)

![image](https://user-images.githubusercontent.com/1456219/113502899-6a235980-9561-11eb-969d-a84164e88d88.png)

**Comment by AB-Y** [comment]
In short term, putting it on bottom-right fit for both mobile and web view.
But leave a new issue #141   to make sure it will be checked again about separate the author name and the date to the second line
