### ISSUE TITLE
文章列表下，每一篇文章的外框、彼此之間的 margin space 調整

### ISSUE THREAD

**Issue by kun-yu-tsai** [nexfoundation/vanilla#112]
在設計中，文章列表的樣式如下
<img width="878" alt="Screenshot 2021-03-30 at 04 06 43" src="https://user-images.githubusercontent.com/9505724/112895020-29fe4a00-910f-11eb-8f22-e9b55665cadb.png">

目前是沒有邊框、文章之間也沒有 margin space
![Screenshot 2021-03-30 at 04 20 50](https://user-images.githubusercontent.com/9505724/112895159-5c0fac00-910f-11eb-8252-ac2d3bffc2c7.png)

要把這個加入。[詳細可以參考設計。](https://www.figma.com/file/rOeaDScRLJ5qUAeAqiz4XO/Forum-Design-Submission?node-id=0%3A1)

**Comment by blueworrybear** [comment]
@kun-yu-tsai @jeffsyliu 

It seems to me that this issue is solved by #118

**Comment by kun-yu-tsai** [comment]
@blueworrybear that's right, awesome. Thanks, Benno! I'll have the QA team (which is me and Abby and Designer) to look into it 😆 😆

**Comment by AB-Y** [comment]
確認沒問題
