### ISSUE TITLE
Layout is Broken after Leaving New Commemt 

### ISSUE THREAD

**Issue by blueworrybear** [nexfoundation/vanilla#119]
**Describe the bug**
After creating a new Commemt, the layou is messed up.

**Comment by AB-Y** [comment]
it works well now.
Mobile view and webview
<img width="954" alt="截圖 2021-04-15 上午3 51 18" src="https://user-images.githubusercontent.com/38776510/114770290-dee66700-9d9d-11eb-85b6-f920c891e5e7.png">
<img width="436" alt="截圖 2021-04-15 上午3 50 59" src="https://user-images.githubusercontent.com/38776510/114770299-e0b02a80-9d9d-11eb-98b8-8144712dc25a.png">
