### ISSUE TITLE
當沒有標籤的時候，將標籤的 display 改成 none，不要佔住空間，變成一塊 top padding。

### ISSUE THREAD

**Issue by kun-yu-tsai** [nexfoundation/vanilla#120]

**Comment by AB-Y** [comment]
確認沒有標籤時，不會有多餘空白空間出現

如圖所示
<img width="1270" alt="截圖 2021-04-15 上午4 19 33" src="https://user-images.githubusercontent.com/38776510/114773579-ce37f000-9da1-11eb-8b0c-22720b046826.png">
<img width="409" alt="截圖 2021-04-15 上午4 19 21" src="https://user-images.githubusercontent.com/38776510/114773582-cf691d00-9da1-11eb-9e5d-3e59b45e7e38.png">
