### ISSUE TITLE
發表新話題的 button，css 更改成設計的模樣

### ISSUE THREAD

**Issue by kun-yu-tsai** [nexfoundation/vanilla#123]
Current
![Screenshot 2021-04-01 at 22 19 14](https://user-images.githubusercontent.com/9505724/113308061-5ea11a00-9338-11eb-9373-04ab93e9ab40.png)

Desired
<img width="305" alt="Screenshot 2021-04-01 at 22 18 47" src="https://user-images.githubusercontent.com/9505724/113308072-6234a100-9338-11eb-8629-189662f3e45b.png">

**Comment by AB-Y** [comment]
已確認目前修改如附圖顯示 style
