### ISSUE TITLE
文章收藏按鈕直接綁定在文章下方的狀態列，上面的收藏 button

### ISSUE THREAD

**Issue by kun-yu-tsai** [nexfoundation/vanilla#124]
就是這兩個畫面：
<img width="945" alt="Screenshot 2021-04-01 at 22 24 12" src="https://user-images.githubusercontent.com/9505724/113310641-0a4b6980-933b-11eb-9af4-b3d6851cbfca.png">

<img width="919" alt="Screenshot 2021-04-01 at 22 23 38" src="https://user-images.githubusercontent.com/9505724/113310673-10414a80-933b-11eb-8339-b2556ebc50a5.png">

理想上，把整個 bookmark button 搬過來，取代掉原本的那個。

意思是，使用者沒有 bookmark 時是長這樣：
<img width="43" alt="Screenshot 2021-04-01 at 22 39 21" src="https://user-images.githubusercontent.com/9505724/113310953-5ac2c700-933b-11eb-801e-27d40184570e.png">

bookmark 後是長這樣：
<img width="29" alt="Screenshot 2021-04-01 at 22 39 24" src="https://user-images.githubusercontent.com/9505724/113310978-63b39880-933b-11eb-9e37-c3dfd7ac0bea.png">

（ps: 我有在想要長這樣，但這個 SVG 的 width 好像要調整，他沒有完全  align with the one above）
<img width="44" alt="Screenshot 2021-04-01 at 22 41 53" src="https://user-images.githubusercontent.com/9505724/113311057-79c15900-933b-11eb-87a5-a3a094277933.png">

這個 ticket 比較麻煩的會是，按下 bookmark 後要去觸發 bookmark counts 的 update and render.

簡單一點的做法是，只要直接 +1 然後 update DOM 就好，不需要還要從 server 那邊 fetch response。

我的想法是這樣做應該就可以，如果有什麼我沒注意到或不妥的，都可以討論唷唷唷～～

**Comment by blueworrybear** [comment]
@kun-yu-tsai 

Hmmm... It seems to me that we also need to update discussion page to align with the design.
Let's do it next week 😎

**Comment by blueworrybear** [comment]
@kun-yu-tsai 

I am on the high-speed rail and feel boring. 😪 
So I update the code and make the bookmark design on the discussion page look as the same as discussions list page.

**Comment by AB-Y** [comment]
<img width="319" alt="截圖 2021-04-09 下午9 24 53" src="https://user-images.githubusercontent.com/38776510/114186992-13ab8600-997a-11eb-932c-c7414ba9538e.png">
確認已儲存書籤 與 尚未儲存至書籤的 icon 樣式符合預期
關閉此 issue
