### ISSUE TITLE
通知偏好設定在手機瀏覽模式下選項被擋住

### ISSUE THREAD

**Issue by AB-Y** [nexfoundation/vanilla#139]

**Comment by AB-Y** [comment]
網頁版本
<img width="1313" alt="截圖 2021-04-05 下午7 45 10" src="https://user-images.githubusercontent.com/38776510/113570957-fa3bce80-9647-11eb-8e92-4c7ff6c923a9.png">


手機版本
<img width="514" alt="截圖 2021-04-05 下午7 49 41" src="https://user-images.githubusercontent.com/38776510/113571008-150e4300-9648-11eb-8446-a45b14395228.png">

目前我覺得要塞兩個選項進去有點難，版面會有點不整齊
是否可以先在手機瀏覽模式下直接隱蔽「通知設定」這個功能
意思是：只限定這個功能在網頁版才能設定

**Comment by AB-Y** [comment]
步驟：
使用手機瀏覽
點擊右上角人像大頭貼
可以選擇「個人資訊」、「通知」、「訊息」（將被移除）
選擇「通知」
右上角有個 filter 符號，隱藏這個功能（如附圖綠線框部分）
<img width="444" alt="截圖 2021-04-08 下午6 20 17" src="https://user-images.githubusercontent.com/38776510/114011108-6c562280-9897-11eb-9c68-bb1cfbe8b8b8.png">

**Comment by kun-yu-tsai** [comment]
這部分，在手機中可以左右滑動，讓在右邊的 checkbox reveal。
