### ISSUE TITLE
mobile view, 移除訊息進入介面

### ISSUE THREAD

**Issue by AB-Y** [nexfoundation/vanilla#149]

**Comment by AB-Y** [comment]
如附圖為 figma 原本設計圖，但因為目前需要先拿掉「訊息」功能
所以手機瀏覽時也先移除進入訊息介面的 icon
<img width="890" alt="截圖 2021-04-08 下午5 57 00" src="https://user-images.githubusercontent.com/38776510/114007768-31062480-9894-11eb-8ace-6b24564b69d7.png">

**Comment by kun-yu-tsai** [comment]
<img src="https://user-images.githubusercontent.com/9505724/114008497-e042fb80-9894-11eb-896a-e3882dd5638b.PNG" width="400">

藍色框框那個要移除掉。

看是先用 visibility:hidden 把那一塊空白下來。還是直接用 display:none（如果他可以直接變成剩下兩個 tab button）

**Comment by blueworrybear** [comment]
This issue relates to #60 .
