### ISSUE TITLE
將「熱門看板」內的各看板連結到分類

### ISSUE THREAD

**Issue by AB-Y** [nexfoundation/vanilla#34]
分類一：下決定之前...
分類二：簽證
分類三：求學
分類四：工作
分類五：海外生活
分類六：你哭得很難看，我也是

**Comment by kun-yu-tsai** [comment]
@jeffsyliu 
category button 部分，只有點到字可以連進去，點周邊的框框內是進不去的。這個需要調整一下～～

**Comment by kun-yu-tsai** [comment]
![Uploading Screenshot 2021-02-08 at 00.36.21.png…]()

**Comment by kun-yu-tsai** [comment]
<img width="280" alt="Screenshot 2021-02-08 at 00 36 21" src="https://user-images.githubusercontent.com/9505724/107394010-5dbcea80-6b36-11eb-978c-b630f6d68544.png">
