### ISSUE TITLE
check global CSS button

### ISSUE THREAD

**Issue by AB-Y** [nexfoundation/vanilla#35]
ref: https://www.figma.com/file/rOeaDScRLJ5qUAeAqiz4XO/Forum-Design-Submission?node-id=1%3A568

**Comment by kun-yu-tsai** [comment]
這個目前進度是~~~ @Civon

**Comment by Civon** [comment]
還沒開動🙈
我明天做 或是有人有更新嗎
我這邊的瑣事告一段落了🏄‍♀️
