### ISSUE TITLE
計算按讚數量（包含文章、comment）

### ISSUE THREAD

**Issue by AB-Y** [nexfoundation/vanilla#40]

**Comment by blueworrybear** [comment]
@kun-yu-tsai @AB-Y 

I have merge a PR to implement this feature.
Here are some problems need to be solved:

- How to render **LikeButton** when the user not login?

    Current approach is to keep the button and has no reaction when user click it.

- Need to add buttons on **Discussions** page (#43)
- Need to add CSS style to fit the design

**Comment by AB-Y** [comment]
> @kun-yu-tsai @AB-Y
> 
> I have merge a PR to implement this feature.
> Here are some problems need to be solved:
> 
> * How to render **LikeButton** when the user not login?
>   Current approach is to keep the button and has no reaction when user click it.

keep the like button, however, when user (not login) clicks it, try to ask him/her to login, which means turn to login page automatically.

> * Need to add buttons on **Discussions** page (#43)

sorry for I cannot get the status. Is that mean the function already works but without icon and numbers to present it, or, this function could not work when reviewing the discussion page?
If is the later one, totally fine, just have another ticket to note it :)
and tag this ticket to the review status.

> * Need to add CSS style to fit the design
try to modify the design on #109 , if you need any help, please let me know 


//close the #43 , put all discussion in this thread

**Comment by AB-Y** [comment]
back to the checking part, 
it works correctly on counting  numbers for articles and comments **on detail page.**
