### ISSUE TITLE
調整 bookmark, share 那一列的 layout，文字置中

### ISSUE THREAD

**Issue by AB-Y** [nexfoundation/vanilla#44]
並且進行排版

**Comment by kun-yu-tsai** [comment]
和這個一起 #78

**Comment by kun-yu-tsai** [comment]
![Uploading Screenshot 2021-03-28 at 17.06.05.png…]()

**Comment by kun-yu-tsai** [comment]
<img width="690" alt="Screenshot 2021-03-28 at 16 46 48" src="https://user-images.githubusercontent.com/9505724/112747423-ec52d180-8fe7-11eb-96af-f59b43ad064a.png">

**Comment by kun-yu-tsai** [comment]
<img width="497" alt="Screenshot 2021-03-28 at 17 06 41" src="https://user-images.githubusercontent.com/9505724/112747431-fa085700-8fe7-11eb-8d05-74ee9d5a2c20.png">

**Comment by AB-Y** [comment]
目前狀態大致上符合設計樣式，因此關閉此 issue
<img width="950" alt="截圖 2021-04-09 下午10 02 27" src="https://user-images.githubusercontent.com/38776510/114191782-5e7bcc80-997f-11eb-9239-a696fdbe28a3.png">


另外，關於時間位置配置，有另外在 #111 提到修改與目前暫時解法
