### ISSUE TITLE
更新 header 上的 NEX logo 

### ISSUE THREAD

**Issue by AB-Y** [nexfoundation/vanilla#46]

**Comment by AB-Y** [comment]
hello, need to change to svg format

**Comment by kun-yu-tsai** [comment]
`<svg width="46" height="21" viewBox="0 0 46 21" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M14.2568 3.70314V18H10.2945L4.86171 11.5051V18H0.164173V3.70314H4.12645L9.55926 10.198V3.70314H14.2568ZM26.9898 0.802914H28.3173L21.5774 20.0424H20.2498L26.9898 0.802914ZM38.2412 6.82802V9.97333H44.5523V13.0982H38.2412V18H34.1973V3.70314H45.4101V6.82802H38.2412Z" fill="white"/>
</svg>`

**Comment by AB-Y** [comment]
@jeffsyliu please help with this

**Comment by kun-yu-tsai** [comment]
水！
