### ISSUE TITLE
移除 search 功能內的 Filter Results

### ISSUE THREAD

**Issue by AB-Y** [nexfoundation/vanilla#47]

**Comment by kun-yu-tsai** [comment]
<img width="1269" alt="Screen Shot 2021-02-23 at 12 51 57 AM" src="https://user-images.githubusercontent.com/9505724/108741389-a7172c00-7571-11eb-85c2-058ba09d9435.png">

**Comment by kun-yu-tsai** [comment]
可能已經拿掉了，再請 @blueworrybear 協助確認
