### ISSUE TITLE
Locales - i18n

### ISSUE THREAD

**Issue by blueworrybear** [nexfoundation/vanilla#5]
**Describe the Feature**

Translate forum to Traditional Chinese. 繁體中文化

**Additional context**

Not sure if there is already i18n addon for Vanilla. Need someone to survey on this feature.

**Comment by Civon** [comment]
SSO add-ons, already hv proudly twnese done this.
https://open.vanillaforums.com/addon/vf_zh_tw-locale
Instruction here
https://success.vanillaforums.com/kb/articles/231-translating-vanilla

![image](https://user-images.githubusercontent.com/24861096/96223712-f09eab80-0fc0-11eb-8092-3ad131587b66.png)

> PS: I'm still solving my env issue, confused why i need to build it before docker up

**Comment by jeffsyliu** [comment]
Use the following Addon:
https://open.vanillaforums.com/addon/vf_zh_tw-locale
