### ISSUE TITLE
先把訊息功能，整個隱藏掉。（第一個版本，不開放發送訊息）

### ISSUE THREAD

**Issue by kun-yu-tsai** [nexfoundation/vanilla#60]
<img width="1299" alt="Screen Shot 2021-02-22 at 10 13 28 PM" src="https://user-images.githubusercontent.com/9505724/108719997-3bc25f80-755b-11eb-8cd0-1d2ef96ebc71.png">

靠右邊訊息那個 button 隱藏起來。

相關 issues，底下 issues 也先不用作
#50 
#49 
#39

**Comment by Civon** [comment]
Thx 包
Reviewed.
