### ISSUE TITLE
這個很重要！手機版本 pop out navigation panel 的內容，目前是空白！

### ISSUE THREAD

**Issue by kun-yu-tsai** [nexfoundation/vanilla#64]
<img width="565" alt="Screenshot 2021-02-08 at 00 09 57" src="https://user-images.githubusercontent.com/9505724/107152345-61b80380-69a2-11eb-963f-f010d7e032ea.png">

目前是空白

要新增以下 navigation 的內容
- po 文的 button
- 分類列表。這部分以「純文字」去呈現，不需要用網頁版的那種 color block。
- 熱門標籤
- NEX 廣告

其實就是把網頁版的 left panel 整個複製到上面
<img width="277" alt="Screenshot 2021-02-08 at 00 13 12" src="https://user-images.githubusercontent.com/9505724/107152392-89a76700-69a2-11eb-806a-7c50ed598acd.png">

**Comment by kun-yu-tsai** [comment]
有簡單的做法，也有複雜的。和 @kun-yu-tsai 討論。

**Comment by kun-yu-tsai** [comment]
菜包我要研究一下怎麼做比較好

**Comment by blueworrybear** [comment]
#### update

- 顯示純文字連結 -> 已找到方法
- 顯示常用 tag -> 已明白如何傳遞PHP變數到 React Component，正在實作
- 顯示廣告 -> 已找到在 sidebar 插入 React Component 的方法。但現在的廣告似乎不適合 mobile view，要重新設計嗎?

Redux 的教學有再更新一次: [Tutorial](https://www.notion.so/nexf/Vanilla-and-Redux-e3a631a2eb034d878c3ce42dcad51fc8)

詳細描述了如何讓PHP 和 Redux 互動。

**Comment by blueworrybear** [comment]
@AB-Y @kun-yu-tsai 

I have resolved this issue, please visit our development server to see the result.
Notice that you may need to clear the cache to see the updated version.

---

#### Update

I found that the sidebar will become empty in the search page.
I will take a look and try to fix it this weekend. 😢

**Comment by kun-yu-tsai** [comment]
我這邊用我的手機測試，沒有問題。請 @AB-Y 也一起測一下唷唷～～

**Comment by kun-yu-tsai** [comment]
Thanks, @blueworrybear! 🍻
