### ISSUE TITLE
熱門標籤後面有數字，以及色碼不對

### ISSUE THREAD

**Issue by kun-yu-tsai** [nexfoundation/vanilla#66]
<img width="288" alt="Screen Shot 2021-02-22 at 6 50 27 PM" src="https://user-images.githubusercontent.com/9505724/108698219-db252980-753e-11eb-99f9-8164b4493c71.png">

1. 後面的數字移除
2. 色碼調整

@jeffsyliu 可能要麻煩你那邊看一下～

**Comment by jeffsyliu** [comment]
1.
The number is the count of articles having the tag.
This is written in `applications/vanilla/modules/class.tagmodule.php`
Can I just modify the module?Or is there a better way to override this if we just want to change our addons.

2.
The color code has been changed.
