### ISSUE TITLE
po 文的那個頁面，直接把標籤顯示出來

### ISSUE THREAD

**Issue by kun-yu-tsai** [nexfoundation/vanilla#67]
http://23.99.124.43/post/discussion

下面的標籤，直接顯示

<img width="740" alt="Screen Shot 2021-02-22 at 6 48 42 PM" src="https://user-images.githubusercontent.com/9505724/108698057-a6b16d80-753e-11eb-9c48-0ea50dc71e5d.png">

把 Show Popular Tags 直接展開（目前是要點擊後才能展開）
展開如下：

<img width="835" alt="Screen Shot 2021-02-22 at 6 48 46 PM" src="https://user-images.githubusercontent.com/9505724/108698068-aa44f480-753e-11eb-8241-f07db8ce30e0.png">

**Comment by blueworrybear** [comment]
@kun-yu-tsai 

I'll take this one.
