### ISSUE TITLE
po 文按鈕按下去，全部導到 http://23.99.124.43/post/discussion

### ISSUE THREAD

**Issue by kun-yu-tsai** [nexfoundation/vanilla#68]
目前有的會導到特定類別的位置，例如：http://23.99.124.43/post/discussion/%E7%B0%BD%E8%AD%89
全部改成這裏 http://23.99.124.43/post/discussion

意思就是不論他在哪個類別，全部都導引到「自行選擇類別」的 po 文

**Comment by blueworrybear** [comment]
@kun-yu-tsai 

I used a quite hacky way to solve this issue because I am trying not to break the vanilla's original codes.

I'm not sure this is a good idea since the code is not easy to read.
Therefore if you think this is not a acceptable coding style, please let me know.

**Comment by kun-yu-tsai** [comment]
@blueworrybear 

Thanks for the heads up. I have looked into the code and I think it shall be all right forcibly setting the category ID to null for now.

I have also appended a comment with it.
