### ISSUE TITLE
footer 要修改

### ISSUE THREAD

**Issue by AB-Y** [nexfoundation/vanilla#74]
**Describe the Feature**

**User Story**

**Acceptance Criteria**

**Additional context**

**Mockups**

**Related Issues**

**Comment by AB-Y** [comment]
@AB-Y 要確認要留什麼

**Comment by kun-yu-tsai** [comment]
This is our current footer. @AB-Y 可以看一下是否 okay.

![Screenshot 2021-04-01 at 22 49 39](https://user-images.githubusercontent.com/9505724/113312131-8b573080-933c-11eb-9ced-4e7f6be96d8c.png)
