### ISSUE TITLE
翻譯，評論 都改成 留言

### ISSUE THREAD

**Issue by kun-yu-tsai** [nexfoundation/vanilla#75]
在很多地方都出現，評論改成留言。
@AB-Y 討論是否要改成「文章」，和你討論

<img width="953" alt="Screen Shot 2021-02-23 at 12 59 03 AM" src="https://user-images.githubusercontent.com/9505724/108742166-666be280-7572-11eb-9cac-20904b2e0d84.png">
<img width="398" alt="Screen Shot 2021-02-23 at 12 59 28 AM" src="https://user-images.githubusercontent.com/9505724/108742180-6966d300-7572-11eb-9c8f-5dfc92d14aed.png">

**Comment by AB-Y** [comment]
經討論，確認將「討論」改「文章」，「評論」改「留言」
