### ISSUE TITLE
在首頁點擊標籤後，左側目錄欄位應維持不變

### ISSUE THREAD

**Issue by AB-Y** [nexfoundation/vanilla#77]
目前點擊分類 跟 點擊標籤後 左側會有不一樣的變動
統一改成左側不變動（仍顯示分類跟標籤選項）
下圖是分類跟標籤都不見了的截圖

<img width="969" alt="截圖 2021-02-24 下午8 47 22" src="https://user-images.githubusercontent.com/38776510/109002935-cf259d00-76e1-11eb-83b5-d121c03a6d40.png">

**Comment by kun-yu-tsai** [comment]
點擊標籤後，左邊 navigation panel 的東西會消失不見。
這部分，要調整成，navigation panel 的東西維持住。

**Comment by kun-yu-tsai** [comment]
菜包和 Jeff 確認，和 Benno update the decision
