### ISSUE TITLE
文章列表中，將各文章所屬的分類放置在相關資訊的第一個位置

### ISSUE THREAD

**Issue by AB-Y** [nexfoundation/vanilla#78]
如截圖，拉到該行的第一個位置。

<img width="1041" alt="截圖 2021-02-24 下午8 55 35" src="https://user-images.githubusercontent.com/38776510/109004000-1a8c7b00-76e3-11eb-9d03-87eee48ba590.png">

**Comment by Civon** [comment]
Just to confirm, Design 上是沒有這個的
是後來追加的還是誤植呢
@kun-yu-tsai @AB-Y

**Comment by kun-yu-tsai** [comment]
@Civon 追加的～～～～感謝確認！
