### ISSUE TITLE
發表新文章，在選擇分類時，不能選擇 Wiki

### ISSUE THREAD

**Issue by kun-yu-tsai** [nexfoundation/vanilla#80]
目前我們不讓一般使用者發表 Wiki 文章

<img width="866" alt="Screen Shot 2021-02-24 at 9 30 18 PM" src="https://user-images.githubusercontent.com/9505724/109007793-7fe26b00-76e7-11eb-9af0-b7318edd4720.png">

**Comment by blueworrybear** [comment]
@kun-yu-tsai @AB-Y 

I found that Vanilla already provides a way to customize user permission.
We could prevent normal user to post new discussions on **Wiki** category.

Although the user will still see the **Wiki** category, but he / she is unable to select it.
Please help to confirm if it fits our requirements or need more enhancements.

![2021-03-24 (1)_LI](https://user-images.githubusercontent.com/1456219/112331429-dd240900-8cf3-11eb-9a16-13fbe1d4908d.jpg)

**Comment by kun-yu-tsai** [comment]
No problem bro. I think it is pretty good for us 👍 . Thanks!

**Comment by AB-Y** [comment]
目前設定是否有誤？
一般 user（沒有特別經後台設定拉高權限）仍可以選擇 wiki 類別並且完成發文動作

**Comment by AB-Y** [comment]
已修正控制台預設一般 user 的身份別，移除註冊後就自動有 wiki editor 的權限。
因此目前這個 issue 確認沒問題：有列出該類別選項，但無法圈選
