### ISSUE TITLE
Search and Excerpt Not Working for Chinese

### ISSUE THREAD

**Issue by blueworrybear** [nexfoundation/vanilla#9]
**Describe the bug**
1. Full Text Search does not work for Chinese
2. Discussion does not work for excerpt

**To Reproduce**
1. Search for `測試`

**Expected behavior**
Should return [#disuccion 5](http://23.99.124.43/discussion/5/%E5%B8%A5%E6%B0%A3%E7%9A%84%E5%9C%A8%E6%8D%B7%E9%81%8B%E4%B8%8A%E6%B8%AC%E8%A9%A6%E4%B8%80%E4%B8%8B#latest)

**Screenshots**
![image](https://user-images.githubusercontent.com/1456219/97082810-00606480-163f-11eb-9596-0e99e2761605.png)
![image](https://user-images.githubusercontent.com/1456219/97082828-166e2500-163f-11eb-8f4b-cb69401e020e.png)

**Additional context**
Nah

**Comment by kun-yu-tsai** [comment]
@blueworrybear 這個是不是搞定了～～～
